<?php

namespace Angie\NotasBundle\Repository;

/**
 * AsignaturaAlumnoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AsignaturaAlumnoRepository extends \Doctrine\ORM\EntityRepository
{
}
