<?php

namespace Angie\NotasBundle\Repository;

/**
 * AsignaturaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AsignaturaRepository extends \Doctrine\ORM\EntityRepository
{
}
