<?php

namespace Angie\NotasBundle\Repository;

/**
 * NotaSemestreAlumnoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotaSemestreAlumnoRepository extends \Doctrine\ORM\EntityRepository
{
}
